apiVersion: v1
kind: Service
metadata:
  name: image-moderation-svc
spec:
  selector:
    app: image-moderation
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5006

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-moderation
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: image-moderation
  template:
    metadata:
      labels: 
        app: image-moderation
    spec:
      containers:
      - name: image-moderation
        image: cc1729/image_moderation:imagemoderation
        ports:
        - containerPort: 5006
